//
//  Achievements.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class Achievements: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _achievementId: String?
    var _detail: String?
    var _image: String?
    
    class func dynamoDBTableName() -> String {

        return "wordonthestreet-mobilehub-915338963-Achievements"
    }
    
    class func hashKeyAttribute() -> String {

        return "_achievementId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_achievementId" : "achievementId",
               "_detail" : "detail",
               "_image" : "image",
        ]
    }
}
