//
//  ApplicationUsers.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.15
//

import Foundation
import UIKit
import AWSDynamoDB

class ApplicationUsers: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _password: String?
    var _phoneNumber: NSNumber?
    var _username: String?
    
    class func dynamoDBTableName() -> String {

        return "wordonthestreet-mobilehub-915338963-ApplicationUsers"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_password" : "password",
               "_phoneNumber" : "phoneNumber",
               "_username" : "username",
        ]
    }
}
