//
//  PlacesVocabulary.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.15
//

import Foundation
import UIKit
import AWSDynamoDB

class PlacesVocabulary: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _placeId: String?
    var _placeType: String?
    var _placeName: String?
    var _usersHere: Set<String>?
    var _wordIds: Set<String>?
    
    class func dynamoDBTableName() -> String {

        return "wordonthestreet-mobilehub-915338963-PlacesVocabulary"
    }
    
    class func hashKeyAttribute() -> String {

        return "_placeId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_placeType"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_placeId" : "placeId",
               "_placeType" : "placeType",
               "_placeName" : "placeName",
               "_usersHere" : "usersHere",
               "_wordIds" : "wordIds",
        ]
    }
}
