//
//  UserVocab.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class UserVocab: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _allWords: [NSObject]?
    var _flashcardWords: [NSObject]?

    class func dynamoDBTableName() -> String {

        return "wordonthestreet-mobilehub-915338963-UserVocab"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_allWords" : "allWords",
               "_flashcardWords" : "flashcardWords",
        ]
    }
}
