//
//  WordPairs.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.15
//

import Foundation
import UIKit
import AWSDynamoDB

class WordPairs: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _wordId: String?
    var _englishWord: String?
    var _spanishWord: String?
    
    class func dynamoDBTableName() -> String {

        return "wordonthestreet-mobilehub-915338963-WordPairs"
    }
    
    class func hashKeyAttribute() -> String {

        return "_wordId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_englishWord"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_wordId" : "wordId",
               "_englishWord" : "englishWord",
               "_spanishWord" : "spanishWord",
        ]
    }
}
